Tarea2AlessandroFavareto/Controllers/GridsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using Tarea2AlessandroFavareto.Models;

namespace Tarea2AlessandroFavareto.Controllers
{
    public class GridsController : Controller
    {

        // GET: Grids
        public ActionResult Index()
        {
            
            if (Session["DatosSesion"] == null)
            {
                var Lenguaje = new List<Grid>();
                string[] Nombres ={
                    "Ada", "Assembly", "C", "C#", "C++", "Cobol", "Dart", "Fortran", 
                    "GDScript", "GameMaker Language", "Go", "Groovy", "Haskell", "Java", 
                    "JavaScript", "Julia", "Kotlin", "Lua", "MATLAB", "Objective-C", 
                    "Perl", "PHP", "Python", "R", "Ruby", "Rust", "Scala", "Swift", 
                    "TypeScript", "Visual Basic"
                };
                for (int i = 0; i < Nombres.Length; i++)
                {
                    Grid grid = new Grid { Posicion = i + 1, Nombre = Nombres[i], ClasificacionMostrar = "0%", PorcentajeMostrar = "0%" };
                    Lenguaje.Add(grid);
                }
                Session["ListaLenguajes"] = Lenguaje;
                var listaOrdenada = Lenguaje.OrderBy(item => item.Clasificacion).Take(20).ToList();
                return View(listaOrdenada);
            }
            else
            {
                /*int VotosTotales = int.Parse(Session["VotosTotales"].ToString());
                Session["VotosTotales"] = VotosTotales++;*/

                Dictionary<int, Encuesta> datosSesion = Session["DatosSesion"] as Dictionary<int, Encuesta>;
                List<Grid> ListaLenguajes = Session["ListaLenguajes"] as List<Grid>;
                string L1 = datosSesion[datosSesion.Count-1].LenguajePrimario;
                string L2 = datosSesion[datosSesion.Count-1].LenguajeSecundario;
                float VotosTotales = 0; 
                foreach (var item in ListaLenguajes)
                {
                    if (L1.Equals(item.Nombre))
                    {
                        item.Votos += 1;
                        
                    }
                    if (L2.Equals(item.Nombre))
                    {
                        item.Votos += .5f;   
                    }
                    VotosTotales += item.Votos;
                }
                foreach (var item in ListaLenguajes)
                {
                    float num = ((item.Votos / VotosTotales) * 100);
                    item.ClasificacionMostrar = num.ToString() + "%";
                    item.Clasificacion = num;
                }
                var listaOrdenada = ListaLenguajes.OrderByDescending(item => item.Clasificacion).ToList();
                int pos = 1;
                foreach (var item in listaOrdenada)
                {

                    item.Posicion = pos;
                    pos++; 
                }
                for (int i = 0; i < listaOrdenada.Count-1; i++)
                {
                    listaOrdenada[i].Porcentaje = listaOrdenada[i].Clasificacion-listaOrdenada[i+1].Clasificacion;
                    if (listaOrdenada[i].Porcentaje>0)
                    {
                        listaOrdenada[i].PorcentajeMostrar = "+" + listaOrdenada[i].Porcentaje + "%";
                    }

                }
  
                listaOrdenada = ListaLenguajes.OrderByDescending(item => item.Clasificacion).Take(20).ToList();
                return View(listaOrdenada);
            }
            
            

            
        }



    }
}

Tarea2AlessandroFavareto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Grids", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tarea 2 Alessandro Favareto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>